# Generated by Django 5.2.2 on 2026-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentprofile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
