# Generated by Django 5.2.9 on 2026-03-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_studentprofile_email_studentprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
