# Generated by Django 5.2.9 on 2026-03-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_organizationprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
