# Generated by Django 5.2.9 on 2026-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_organizationprofile_email_organizationprofile_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
