# Generated by Django 5.2.9 on 2026-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_organizationprofile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
