# Generated by Django 5.2.9 on 2026-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_organizationprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
