# Generated by Django 5.2.2 on 2025-12-28 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='meeting_format',
            field=models.CharField(choices=[('ONLINE', 'online'), ('IN_PERSON', 'in person'), ('HYBRID', 'hybrid')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
