# Generated by Django 5.2.2 on 2025-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_created_at_project_meeting_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
