# Generated by Django 5.2.2 on 2026-01-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentprofile_year'),
        ('project', '0004_projectapplication_message_projectapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='profiles.studentprofile'),
        ),
    ]
