# Generated by Django 5.2.2 on 2026-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_created_by_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'completed'), ('REMOVED', 'removed')], default='PENDING', max_length=10),
        ),
    ]
