# Generated by Django 5.2.2 on 2026-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technical Skills'), ('SOFT', 'Soft Skills'), ('TOOLS', 'Tools & Technologies')], default='TECH', max_length=50),
            preserve_default=False,
        ),
    ]
